services:
  - type: web
    name: yandex-music-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
